document.write ('<table width="100" border="0" cellpadding="0" cellspacing="0">\n');
document.write ('      <tr>\n');
document.write ('        <td><img src="/uwc/uwc/images_tw/Downloads_02.jpg" width="177" height="171" /></td>\n');
document.write ('      </tr>\n');
document.write ('    </table>\n');
document.write ('      <table width="177" border="0" cellpadding="0" cellspacing="0">\n');
document.write ('        <tr>\n');
document.write ('          <td><img src="/uwc/uwc/images_tw/inTheme_07.gif" width="177" height="1" /></td>\n');
document.write ('        </tr>\n');
document.write ('        <tr>\n');
document.write ('          <td height="28">　<a href="docs.html" class="product">產品文件</a></td>\n');
document.write ('        </tr>\n');
document.write ('        <tr>\n');
document.write ('          <td><img src="/uwc/uwc/images_tw/inTheme_07.gif" width="177" height="1" /></td>\n');
document.write ('        </tr>\n');
document.write ('        <tr>\n');
document.write ('          <td height="28">　<a href="manuals.html" class="product">使用手冊</a></td>\n');
document.write ('        </tr>\n');
document.write ('        <tr>\n');
document.write ('          <td><img src="/uwc/uwc/images_tw/inTheme_07.gif" width="177" height="1" /></td>\n');
document.write ('        </tr>\n');
document.write ('      </table>\n');