document.write ('<table width="100" border="0" cellpadding="0" cellspacing="0">\n');
document.write ('      <tr>\n');
document.write ('        <td><img src="/uwc/uwc/images_tw/FAQ_02.jpg" width="177" height="171" /></td>\n');
document.write ('      </tr>\n');
document.write ('    </table>\n');
document.write ('      <table width="177" border="0" cellpadding="0" cellspacing="0">\n');
document.write ('        <tr>\n');
document.write ('          <td><img src="/uwc/uwc/images_tw/inTheme_07.gif" width="177" height="1" /></td>\n');
document.write ('        </tr>\n');
document.write ('        <tr>\n');
document.write ('          <td height="28">　<a href="bizs.html" class="product">業務申請</a></td>\n');
document.write ('        </tr>\n');
document.write ('        <tr>\n');
document.write ('          <td><img src="/uwc/uwc/images_tw/inTheme_07.gif" width="177" height="1" /></td>\n');
document.write ('        </tr>\n');
document.write ('        <tr>\n');
document.write ('          <td height="28">　<a href="tech.html" class="product">技術支援</a></td>\n');
document.write ('        </tr>\n');
document.write ('        <tr>\n');
document.write ('          <td><img src="/uwc/uwc/images_tw/inTheme_07.gif" width="177" height="1" /></td>\n');
document.write ('        </tr>\n');
document.write ('     </table>\n');