document.write ('<table width="937" border="0" align="center" cellpadding="0" cellspacing="0">\n');
document.write ('  <tr>\n');
document.write ('    <td height="66" align="center" valign="top"><table width="800" border="0" cellpadding="0" cellspacing="0">\n');
document.write ('      <tr>\n');
document.write ('        <td width="145" height="43" align="right"><img src="https://hibox.hinet.net/uwc/uwc/images_tw/icon-HiNet.gif" width="126" height="50" />\n');
document.write ('                           </td>\n');
document.write ('        <td width="655" align="left" valign="middle" class="front-copyright">中華電信股份有限公司地址：臺北市信義路一段21號 服務時間：24小時全年無休\n');
document.write ('                                  <br />\n');
document.write ('                                  全區免費客戶服務電話：0800-080-365\n'); 
document.write (' 		                         <br />\n');
document.write ('                                 © Chunghwa Telecom Co., Ltd. All Rights Reserved.</td>\n');
document.write ('      </tr>\n');
document.write ('    </table>\n');
document.write (' </td>\n');
document.write ('  </tr>\n');
document.write ('</table>\n');
