document.write ('<table width="633" height="145" border="0" cellpadding="0" cellspacing="0" class="ul">\n');
document.write ('  <tr>\n');
document.write ('    <td height="145" align="left" valign="top"><ul>\n');
document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new63" class="language"><img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" /> hiBox於111/2/15 15:20~19:40發生網路異常，期間webmail/pop/imap/smtp服務無法連線...</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new62" class="language"><img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" /> hiBox大陸地區客戶服務電話於110/12/31下架</a></li>\n');
document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new60" class="language"> <img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" />為提升安全性，將自2022/1/1起停止支援CBC加密連線演算法...</a></li>\n');
document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new56" class="language"> 為了保護您的資料安全，建議使用支援TLS1.2加密傳輸協定的作業系統</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new55" class="language"><img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" /> hiBox將於2020/9/1 14:30~16:30進行網路維護作業，期間大陸收信主機可能出現短暫無法登入...</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new54" class="language"><img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" /> hiBox將於2020/8/30 00:00~06:00進行主機維護作業，期間可能出現短暫無法登入...</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new50" class="language"> 為提升安全性，將自2020/2/12起陸續停用TLS1.0、TLS1.1及weak ciphers...</a></li>\n');
document.write ('      <li><a href="/uwc/uwc/homepage_tw/smsotp.html" class="language"> 郵件簡訊OTP密碼鎖，讓您的hiBox信箱更安全!</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new47" class="language"><img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" /> hiBox系統於2018/12/09 00:00~04:00進行網路維護作業，期間可能出現短暫無法連線現象...</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new46" class="language"> hiBox於2018/09/30 00:00進行廣州主機IP更換</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new43" class="language"> 自2018/12/1起hiBox將停用3DES加密，WinXP使用IE8(含)版本以下瀏覽器，將無法正常顯示網頁，建議您立即選用其他瀏覽器...</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new44" class="language"><img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" /> 6/4 18:00~18:40間收到的信件寄件者與收件者可能會多出現 &lt;xxxx&gt;@hibox.hinet.net...</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new45" class="language"> hiBox提供的聯絡人、行事曆資料已可同步至行動裝置...</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new42" class="language"><img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" /> hiBox系統於2018/03/25 06:00~10:00進行網路維護作業，期間可能出現短暫無法連線現象...</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new41" class="language"><img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" /> 9/4 19:06~20:00 因HiNet DNS異常，導致服務受影響...</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new40" class="language"><img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" /> hiBox 將於2017/5/20 23:30~ 2017/5/21 05:00進行系統例行維護...</a></li>\n');
document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new36" class="language"> hiBox 舊平台客戶服務升版申請自2016年1月12日開放，請至管理系統登錄申請，謝謝!</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new39" class="language"> Outlook 2016 POP3收取信件出現重複收信或信件被刪除問題說明...</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new38" class="language"> hiBox 手機App 於2016/2/3 終止服務，並同時提供新的手機同步方式，不便之處，敬請見諒 !</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new34" class="language"> hiBox自2015年11月16日起，開放舊平台客戶試用新平台。詳細資訊，請登入管理系統查詢。</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new33" class="language"> 親愛的客戶您好: hiBox 為提供客戶更好、更完整的服務，自104年11月1日起提供新版服務平台。</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new31" class="language"><img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" /> hiBox系統於104/06/14 00:00~01:00更新資安設備軔體，期間可能出現短暫無法連線或者連線中斷現象...</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new29" class="language"> hiBox系統己啟用新的資安機制：「webmail登入IP過濾」、「重要設定異動通知」...</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new28" class="language"> hiBox系統已啟用新的資安機制：「Webmail圖形碼驗證機制」、「虛擬鍵盤功能」...</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new27" class="language"><img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" />  因來自大陸之網路連線數量激增，目前從國外連往國內(.tw 或 .hinet.net 網域的網站)皆有極高的機率無法正常開啟網頁...</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/promotion02.html" class="language"> 歡慶十周年，服務升級，信箱空間1G起。.... </a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new23" class="language"> 請務必妥善保護您的信箱密碼，以防範駭客竊信行為.... </a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new22" class="language"> hiBox  iPhone 版行動APP服務 正式推出！.... </a></li>\n');
//document.write ('      <li><a href="http://202.39.47.219/student/index.asp?ct=22" class="language" target=_blank> hiBox教育訓練台中場開張了，免費報名參加，每場限20名，來就送精美贈品。</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new21" class="language"> hiBox行動辦公室升級了- Android版「行動APP服務」正式推出！.... </a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new20" class="language"><img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" /> hiBox 將於 100/9/4(日)凌晨1:00進行系統擴充工程，將停止提供 Webmail、POP3、SMTP與IMAP等服務... </a></li>\n');
document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new19" class="language">【hiBox系統管理員的小叮嚀】為防範駭客盜用您的hiBox帳號，建議您「強度較高」的密碼組合！</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new18" class="language"><img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" /> hiBox送發傳真服務將於6/18(六)9:00AM~16:00PM進行年度主機維護(接收傳真不受影響)....</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new17" class="language">HiBox 大陸地區服務電話號碼異動，新電話號碼為:21-52305900，電話號碼改變，服務品質不變....</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new16" class="language"><img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" /> 因大陸端網路連線台灣網站發生異常情形，請修改hiBox連線設定....</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new15" class="language">「大桃園及台南地區」客戶新選擇，hiBox傳真型信箱開放032及06區碼囉！....</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new14" class="language">hiBox全球郵件傳輸品質大躍進- 美國機房建置完成....</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new13" class="language">11月6日21:00~11月7日1:00 上海機房暫停服務公告....</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new12" class="language">歡慶 hiBox全新加值服務－「雲端郵件備份服務」上線，好康三連送！.... </a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new11" class="language">hiBox兩岸郵件傳輸品質大躍進- 廣州機房建置完成....</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new10" class="language">hiBox新版產品網站暨上海客服專線正式啟用！....</a></li>\n');
//??document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new09" class="language">您有信箱空間不夠用的煩惱嗎？hiBox大容量信箱升級方案....</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new06" class="language">hiBox傳真型信箱，即日起開放03區碼供「大新竹」地區客戶選用....</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new03" class="language">近日發現許多hiBox用戶的帳號被盜用，被盜用的帳號都是帳號與密碼設定相同.... </a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new02" class="language">如果您無法登入hiBox，請您改至www3.hibox.hinet.net 登入，或登入後出現，或登入後出現.... </a></li>\n');
//document.write ('      <li><img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" /> hiBox 將於08月22日凌晨 4 點 30 分至 5 點進行系統維護，其間系統將暫停服務，不便之處，敬請見諒。</li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_tw/news.html#new01" class="language">人緣太好怎麼辦？現在一次申請五個年繳帳號，就送簡訊300通！ </a></li>\n');
document.write (' 	 </ul></td>\n');
document.write ('  </tr>\n');
document.write ('</table>\n');

