document.write ('<table width="100" border="0" cellpadding="0" cellspacing="0">\n');
document.write ('      <tr>\n');
document.write ('        <td><img src="/uwc/uwc/images_en/Downloads_02.jpg" width="177" height="171" /></td>\n');
document.write ('      </tr>\n');
document.write ('    </table>\n');
document.write ('      <table width="177" border="0" cellpadding="0" cellspacing="0">\n');
document.write ('        <tr>\n');
document.write ('          <td><img src="/uwc/uwc/images_en/inTheme_07.gif" width="177" height="1" /></td>\n');
document.write ('        </tr>\n');
document.write ('        <tr>\n');
document.write ('          <td height="28">　<a href="/uwc/uwc/homepage_en/docs.html" class="product">Product Specs.</a></td>\n');
document.write ('        </tr>\n');
document.write ('        <tr>\n');
document.write ('          <td><img src="/uwc/uwc/images_en/inTheme_07.gif" width="177" height="1" /></td>\n');
document.write ('        </tr>\n');
document.write ('        <tr>\n');
document.write ('          <td height="28">　<a href="/uwc/uwc/homepage_en/manuals.html" class="product">User Manual</a></td>\n');
document.write ('        </tr>\n');
document.write ('        <tr>\n');
document.write ('          <td><img src="/uwc/uwc/images_en/inTheme_07.gif" width="177" height="1" /></td>\n');
document.write ('        </tr>\n');
document.write ('      </table>\n');