document.write ('<table width="937" border="0" align="center" cellpadding="0" cellspacing="0">\n');
document.write ('  <tr>\n');
document.write ('    <td height="66" align="center" valign="top"><table width="800" border="0" cellpadding="0" cellspacing="0">\n');
document.write ('      <tr>\n');
document.write ('        <td width="145" height="43" align="right"><img src="https://hibox.hinet.net/uwc/uwc/images_en/icon-HiNet.gif" width="126" height="50" />\n');
document.write ('                           </td>\n');
document.write ('        <td width="655" align="left" valign="middle" class="front-copyright">Chunghwa Telecom Co., Ltd. : No.21,Sec.1,Xinyi Rd.,Zhongzheng Dist.,Taipei City 100, Taiwan\n');
document.write ('                                  <br />\n');
document.write ('                                  HiBox 24/7 Toll-Free Customer Service: 0800-080-365\n'); 
document.write (' 		                         <br />\n');
document.write ('                                 © Chunghwa Telecom Co., Ltd. All Rights Reserved.</td>\n');
document.write ('      </tr>\n');
document.write ('    </table>\n');
document.write (' </td>\n');
document.write ('  </tr>\n');
document.write ('</table>\n');