document.write ('<table width="100" border="0" cellpadding="0" cellspacing="0">\n');
document.write ('      <tr>\n');
document.write ('        <td><img src="/uwc/uwc/images_en/inTheme_02.jpg" width="177" height="171" /></td>\n');
document.write ('      </tr>\n');
document.write ('    </table>\n');
document.write ('      <table width="177" border="0" cellpadding="0" cellspacing="0">\n');
document.write ('        <tr>\n');
document.write ('          <td><img src="/uwc/uwc/images_en/inTheme_07.gif" width="177" height="1" /></td>\n');
document.write ('        </tr>\n');
document.write ('        <tr>\n');
document.write ('          <td height="28">　<a href="/uwc/uwc/homepage_en/features.html" class="product">Features</a></td>\n');
document.write ('        </tr>\n');
document.write ('        <tr>\n');
document.write ('          <td><img src="/uwc/uwc/images_en/inTheme_07.gif" width="177" height="1" /></td>\n');
document.write ('        </tr>\n');
document.write ('        <tr>\n');
document.write ('          <td height="28">　<a href="/uwc/uwc/homepage_en/functions.html" class="product">Types</a></td>\n');
document.write ('        </tr>\n');
document.write ('        <tr>\n');
document.write ('          <td><img src="/uwc/uwc/images_en/inTheme_07.gif" width="177" height="1" /></td>\n');
document.write ('       </tr>\n');
document.write ('        <tr>\n');
document.write ('          <td height="28">　<a href="/uwc/uwc/homepage_en/advantages.html" class="product">Advantages</a></td>\n');
document.write ('        </tr>\n');
document.write ('        <tr>\n');
document.write ('          <td><img src="/uwc/uwc/images_en/inTheme_07.gif" width="177" height="1" /></td>\n');
document.write ('        </tr>\n');
document.write ('        <tr>\n');
document.write ('          <td height="28">　<a href="/uwc/uwc/homepage_en/benefits.html" class="product">Benefit</a></td>\n');
document.write ('        </tr>\n');
document.write ('        <tr>\n');
document.write ('          <td><img src="/uwc/uwc/images_en/inTheme_07.gif" width="177" height="1" /></td>\n');
document.write ('        </tr>\n');
document.write ('       <tr>\n');
document.write ('          <td height="28"><table width="100%" border="0" cellpadding="0" cellspacing="0">\n');
document.write ('       <tr>\n');
document.write ('          <td height="28" valign="bottom">　<span class="front-redB">Value-Added Service</span></td>\n');
document.write ('       </tr>\n');
document.write ('       <tr>\n');
document.write ('       <td height="52" align="right" valign="top">\n');
document.write ('       <table width="90%" border="0" cellpadding="0" cellspacing="0">\n');
document.write ('       <tr>\n');
document.write ('       <td height="47" colspan="2"  align="left" valign="top">\n');
document.write ('       <img src="/uwc/uwc/images_en/icon-06.gif" width="7" height="13" /> <a href="backup.html" class="product">Mail Archiving</a></td>\n');
/*
document.write ('       <img src="/uwc/uwc/images_en/icon-06.gif" width="7" height="13" /> <a href="vas.html" class="product">Push Mail</a></td>\n');
*/
document.write ('       </tr>\n');
document.write ('       </table></td>\n');
document.write ('       </tr>\n');
document.write ('       </table></td>\n');
document.write ('        </tr>\n');
document.write ('        <tr>\n');
document.write ('          <td><img src="/uwc/uwc/images_en/inTheme_07.gif" width="177" height="1" /></td>\n');
document.write ('        </tr>\n');
document.write ('      </table>\n');