document.write ('<table width="633" height="145" border="0" cellpadding="0" cellspacing="0" class="ul">\n');
document.write ('  <tr>\n');
document.write ('    <td height="145" align="left" valign="top"><ul>\n');
document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new63" class="language"><img src="/uwc/uwc/images_cn/icon-new.gif" width="29" height="13" border="0" /> hiBox于20221/2/15 15:20~19:40发生网络异常，期间webmail/pop/imap/smtp服务无法联机...</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new62" class="language"><img src="/uwc/uwc/images_cn/icon-new.gif" width="29" height="13" border="0" /> hiBox大陆地区客户服务电话于110/12/31下架</a></li>\n');
document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new60" class="language"> <img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" />为提升安全性，将自2022/1/1起停止支持CBC加密连线算法...</a></li>\n');
document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new56" class="language"> 为了保护您的数据安全，建议使用支持TLS1.2加密传输协议的操作系统</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new49" class="language"><img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" /> hiBox系统于2019/12/22 00:00~08:00进行网络维护作业，期间可能出现短暂无法联机现象...</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new55" class="language"><img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" /> hiBox将于2020/9/1 14:30~16:30进行网络维护作业，大陆主机期间可能出现短暂无法登入...</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new54" class="language"><img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" /> hiBox将于2020/8/30 00:00~06:00进行主机维护作业，期间可能出现短暂无法登入...</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new50" class="language"> 为提升安全性，将自2020/2/12起陆续停用TLS1.0、TLS1.1及weak ciphers...</a></li>\n');
document.write ('      <li><a href="/uwc/uwc/homepage_cn/smsotp.html" class="language"> 邮件简讯OTP密码锁，让您的hiBox信箱更安全!</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new47" class="language"><img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" /> hiBox系统于2018/12/09 00:00~04:00进行网络维护作业，期间可能出现短暂无法联机现象...</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new46" class="language"><img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" /> hiBox于2018/09/30 00:00进行广州主机IP更换</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new44" class="language"><img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" /> 6/4 18:00~18:40间收到的信件发件人与收件者可能会多出现 &lt;xxxx&gt;@hibox.hinet.net...</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new43" class="language"> 自2018/12/1起hiBox将停用3DES加密，WinXP使用IE8(含)版本以下浏览器，将无法正常显示网页，建议您立即选用其他浏览器...</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new45" class="language"> hiBox提供的联络人、行事历数据已可同步至行动装置...</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new42" class="language"><img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" /> hiBox系统于2018/04/28 00:00~04:00进行主机维护作业，期间可能出现短暂无法联机现象...</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new42" class="language"><img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" /> hiBox系统于2018/03/25 06:00~10:00进行网络维护作业，期间可能出现短暂无法联机现象...</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new41" class="language"><img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" /> 9/4 19:06~20:00 因HiNet DNS异常，导致服务受影響...</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new40" class="language"><img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" /> hiBox 将于2017/5/20 23:30~ 2017/5/21 05:00进行系统例行维护...</a></li>\n');
document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new36" class="language"> hiBox 旧平台客户服务升版申请自2016年1月12日开放，请至管理系统登录申请，谢谢!</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new39" class="language"> Outlook 2016 POP3收取信件出现重复收信或信件被删除问题说明...</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new38" class="language"> HIBOX手机应用程序于2016年2月3日终止服务，并同时提供新的手机同步方式，不便之处，敬请见谅！</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new37" class="language"><img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" /> hiBox将于2016年1月31日凌晨0:15~0:45進行系統例行維護，期間將造成部分用戶無法使用服務...</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new34" class="language"> hiBox自2015年11月16日起，开放旧平台客户试用新平台。详细资讯，请登入管理系统查询。</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new33" class="language"> 亲爱的客户您好: hiBox 为提供客户更好、更完整的服务，自104年11月1日起提供新版服务平台。</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new31" class="language"><img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" /> hiBox系统于104/06/14 00:00~01:00更新资安设备轫体，期间可能出现短暂无法联机或者联机中断现象...</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new29" class="language"> hiBox系统己启用新的资安机制：「webmail登入IP过滤」、「重要设定异动通知」...</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new28" class="language"> hiBox系统已启用新的资安机制：「Webmail图形码验证机制」、「虚拟键盘功能」...</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new27" class="language"><img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" />  因来自大陆之网络联机数量激增，目前从国外连往国内(.tw 或 .hinet.net 网域的网站)皆有极高的机率无法正常开启网页...</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/promotion02.html" class="language"> 欢庆十周年，服务升级，信箱空间1G起。.... </a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new23" class="language"> 请务必妥善保护您的信箱密码，以防范黑客窃信行为.... </a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new22" class="language"> hiBox  iPhone 版行动APP服务 正式推出！.... </a></li>\n');
//document.write ('      <li><a href="http://202.39.47.219/student/index.asp?ct=22" class="language" target=_blank> hiBox教育训练台中场开张了，免费报名参加，每场限20名，来就送精美赠品。</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new21" class="language"> hiBox行动办公室升级了- Android版「行动APP服务」正式推出！.... </a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new20" class="language"><img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" /> hiBox 将于 100/9/4(日)凌晨1:00进行系统扩充工程，将停止提供 Webmail、POP3、SMTP与IMAP等服务... </a></li>\n');
document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new19" class="language">【hiBox系统管理员的小叮咛】为防范黑客盗用您的hiBox账号，建议您「强度较高」的密码组合！</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new18" class="language"><img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" /> hiBox送发传真服务将于6/18(六)9:00AM~16:00PM进行年度主机维护(接收传真不受影响)....</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new17" class="language">HiBox 大陆地区服务电话号码异动，新电话号码为:21-52305900，电话号码改变，服务质量不变....</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new16" class="language"><img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" /> 因大陆端网络联机台湾网站发生异常情形，请修改hiBox联机设定....</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new15" class="language">「大桃园及台南地区」客户新选择，hiBox传真型信箱开放032及06区码啰！....</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new14" class="language">hiBox全球邮件传输质量大跃进- 美国机房建置完成....</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new13" class="language">11月6日21:00~11月7日1:00 上海机房暂停服务公告....</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new12" class="language">欢庆 hiBox全新加值服务－「云端邮件备份服务」上线，好康三连送！.... </a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new11" class="language">hiBox两岸邮件传输质量大跃进- 广州机房建置完成....</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new10" class="language">hiBox新版产品网站暨上海客服专线正式启用！....</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new09" class="language">您有信箱空间不够用的烦恼吗？hiBox大容量信箱升级方案....</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new06" class="language">hiBox传真型信箱，即日起开放03区码供「大新竹」地区客户选用....</a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new03" class="language">近日发现许多hiBox用户的账号被盗用，被盗用的账号都是账号与密码设定相同.... </a></li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new02" class="language">如果您无法登入hiBox，请您改至www3.hibox.hinet.net 登入，或登入后出现，或登入后出现.... </a></li>\n');
//document.write ('      <li><img src="/uwc/uwc/images_tw/icon-new.gif" width="29" height="13" border="0" /> hiBox 将于08月22日凌晨 4 点 30 分至 5 点进行系统维护，其间系统将暂停服务，不便之处，敬请见谅。</li>\n');
//document.write ('      <li><a href="/uwc/uwc/homepage_cn/news.html#new01" class="language">人缘太好怎么办？现在一次申请五个年缴账号，就送简讯300通！ </a></li>\n');
document.write (' 	 </ul></td>\n');
document.write ('  </tr>\n');
document.write ('</table>\n');

