document.write ('<table width="100" border="0" cellpadding="0" cellspacing="0">\n');
document.write ('      <tr>\n');
document.write ('        <td><img src="/uwc/uwc/images_cn/inTheme_02.jpg" width="177" height="171" /></td>\n');
document.write ('      </tr>\n');
document.write ('    </table>\n');
document.write ('      <table width="177" border="0" cellpadding="0" cellspacing="0">\n');
document.write ('        <tr>\n');
document.write ('          <td><img src="/uwc/uwc/images_cn/inTheme_07.gif" width="177" height="1" /></td>\n');
document.write ('        </tr>\n');
document.write ('        <tr>\n');
document.write ('          <td height="28">　<a href="features.html" class="product">产品特色</a></td>\n');
document.write ('        </tr>\n');
document.write ('        <tr>\n');
document.write ('          <td><img src="/uwc/uwc/images_cn/inTheme_07.gif" width="177" height="1" /></td>\n');
document.write ('        </tr>\n');
document.write ('        <tr>\n');
document.write ('          <td height="28">　<a href="functions.html" class="product">功能说明</a></td>\n');
document.write ('        </tr>\n');
document.write ('        <tr>\n');
document.write ('          <td><img src="/uwc/uwc/images_cn/inTheme_07.gif" width="177" height="1" /></td>\n');
document.write ('       </tr>\n');
document.write ('        <tr>\n');
document.write ('          <td height="28">　<a href="advantages.html" class="product">服务优势</a></td>\n');
document.write ('        </tr>\n');
document.write ('        <tr>\n');
document.write ('          <td><img src="/uwc/uwc/images_cn/inTheme_07.gif" width="177" height="1" /></td>\n');
document.write ('        </tr>\n');
document.write ('        <tr>\n');
document.write ('          <td height="28">　<a href="benefits.html" class="product">使用效益</a></td>\n');
document.write ('        </tr>\n');
document.write ('        <tr>\n');
document.write ('          <td><img src="/uwc/uwc/images_cn/inTheme_07.gif" width="177" height="1" /></td>\n');
document.write ('        </tr>\n');
document.write ('       <tr>\n');
document.write ('          <td height="28"><table width="100%" border="0" cellpadding="0" cellspacing="0">\n');
document.write ('       <tr>\n');
document.write ('       <td height="28" valign="bottom">　<span class="front-redB">加值服务</span></td>\n');
document.write ('       </tr>\n');
document.write ('       <tr>\n');
document.write ('       <td height="52" align="right" valign="top">\n');
document.write ('       <table width="90%" border="0" cellpadding="0" cellspacing="0">\n');
document.write ('       <tr>\n');
document.write ('       <td height="47" colspan="2"  align="left" valign="top">\n');
document.write ('       <img src="/uwc/uwc/images_cn/icon-06.gif" width="7" height="13" /> <a href="audit.html" class="product">邮件稽核</a><br />\n');
document.write ('       <img src="/uwc/uwc/images_cn/icon-06.gif" width="7" height="13" /> <a href="backup.html" class="product">邮件备份</a><br />\n');
document.write ('       <img src="/uwc/uwc/images_cn/icon-06.gif" width="7" height="13" /> <a href="smsotp.html" class="product">简讯OTP</a></td>\n');
/*
document.write ('       <img src="/uwc/uwc/images_cn/icon-06.gif" width="7" height="13" /> <a href="vas.html" class="product">快递邮</a></td>\n');
*/
document.write ('       </tr>\n');
document.write ('       </table></td>\n');
document.write ('       </tr>\n');
document.write ('       </table></td>\n');
document.write ('        </tr>\n');
document.write ('        <tr>\n');
document.write ('          <td><img src="/uwc/uwc/images_cn/inTheme_07.gif" width="177" height="1" /></td>\n');
document.write ('        </tr>\n');
document.write ('      </table>\n');
